import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f0f4f8',
        padding: 20,
        justifyContent: 'center',
      },
      header: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#2f3640',
        marginBottom: 20,
        textAlign: 'center',
        textShadowColor: '#dcdde1',
        textShadowOffset: { width: 1, height: 1 },
        textShadowRadius: 3,
      },
      subHeader: {
        fontSize: 22,
        fontWeight: '600',
        color: '#353b48',
        marginBottom: 15,
        textAlign: 'center',
      },
      input: {
        backgroundColor: '#ffffff',
        padding: 15,
        borderRadius: 12,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
        elevation: 3,
      },
      card: {
        backgroundColor: '#ffffff',
        borderRadius: 15,
        padding: 20,
        marginVertical: 10,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 3 },
        elevation: 5,
        borderLeftWidth: 5,
        borderColor: '#00cec9',
      },
      metric: {
        fontSize: 16,
        color: '#2d3436',
        marginBottom: 5,
      },
      button: {
        backgroundColor: '#0984e3',
        padding: 15,
        borderRadius: 30,
        alignItems: 'center',
        marginTop: 10,
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 3 },
        elevation: 5,
      },
      buttonText: {
        color: '#ffffff',
        fontWeight: 'bold',
        fontSize: 18,
      },
      secondaryButton: {
        backgroundColor: '#74b9ff',
        padding: 12,
        borderRadius: 25,
        alignItems: 'center',
        marginTop: 10,
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
        elevation: 3,
      },
      secondaryButtonText: {
        color: '#ffffff',
        fontWeight: '500',
        fontSize: 16,
      },
      metricInput: {
        borderWidth: 1,
        borderColor: '#dfe6e9',
        borderRadius: 12,
        padding: 10,
        backgroundColor: '#ffffff',
        marginTop: 8,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 4,
        shadowOffset: { width: 0, height: 2 },
        elevation: 3,
      }
})